-- tablas de soporte para la simulacion
create table persona (
    p_id                   number generated by default on null as identity,
    --direccion              VARCHAR2(50 CHAR) NOT NULL,
    foto                   BLOB,
    lugar                  number NOT NULL,
    tipo_cliente           number NOT NULL,
    ip                     informacion_personal NOT NULL,
    -- clave primaria de la tabla
    PRIMARY KEY (p_id)
);
/