-- creacion de las tablas a utilizar
create table cliente(
    C_ID                  number generated by default on null as identity,
    datos_personales    informacion_personal
);
/

-- inserts en las tablas
insert into cliente values(default, informacion_personal(
    '30859685',
    'Pedro',
    'Alfonzo',
    'Abdul',
    'Witt',
    informacion_personal.verificar_correo('pedro12@gmail.com'),
    '01-JAN-1950',
    'M',
    'Transilvania' 
));
/

insert into cliente values(default, informacion_personal(
    '30859885',
    'Ricardo',
    'Song',
    'Rodriguez',
    'Wong',
    informacion_personal.verificar_correo('pedro12@correoInvalido.com'),
    '01-01-1960',
    'M',
    'Transilvania' 
));
/

-- selects 
select 
    c.C_ID,
    c.datos_personales.IP_cedula,
    c.datos_personales.IP_Primer_Nombre,
    c.datos_personales.IP_Segundo_Nombre,
    c.datos_personales.IP_Primer_Apeliido,
    c.datos_personales.IP_Segundo_Apellido,
    c.datos_personales.IP_Correo,
    c.datos_personales.IP_Fecha_Nacimiento,
    c.datos_personales.IP_Sexo,
    c.datos_personales.IP_Direccion
from cliente c;

-- drop de todas las tablas y TDA usados para poder ejecutar nuevamente el 
drop table cliente;